### ISSUE TITLE
regenerating icons during build

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#10]
It seems a little unconventional to have checked-in files in the `build` subdirectory, so I'm trying to modify the example `Makefile` to generate the icons during the build process, but can't match the compressed ones that are checked in.  For instance, `examples/timer/home.png` compressed to a 14x14 RLE image is 106 bytes, while the checked in version is 74 bytes.  What parameters where used to generate it?

The checked in `!icon_lg` and `!icon_sm` are both 44x44, although the large one is 652 bytes and the small one is 628. What is different between them? (Looking at the images after uncompression, maybe they were generated from different inputs?)

Is there any documentation on how these various icon files are used and some best practices for drawing them?

**Comment by osresearch** [comment]
Experimentally I've determined that `!icon_lg` is used for the app when it is highlighted in the menu and `!icon_sm` is used when it is not.

**Comment by dakhnod** [comment]
you are right about the hightlighting part in the menu.

Not sure about best practices, the input images need to be in RGBA format I think.
