### ISSUE TITLE
Where do the logs go?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#11]
In the `timer` and `snake` examples there are calls to log messages with `req_data()`.  Where do these go? Is it possible to view them on the phone or via `adb`?

**Comment by arjan-s** [comment]
They're sent to Gadgetbridge, which doesn't recognize the requests and in turn logs them, so you can read them over adb.

**Comment by osresearch** [comment]
How do you read the logs?

**Comment by arjan-s** [comment]
I forgot to mention: you need to be running a debug build of Gadgetbridge, because official builds won't log to adb. So in short that means building your own Gadgetbridge with Android Studio and running that instead of the F-Droid build.

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/184237026-6ad44f92-cd8f-4ad1-90f0-e8fe32890ec6.png)

I'm running my own Gadgetbridge build anyway since my Skagen Gen 6 Hybrid isn't supported in mainline yet.

**Comment by dakhnod** [comment]
@osresearch the newest Gadgetbridge code should have basic support for the Gen6.

For the req_data stuff you need to look out for log messages containing "Unhandled request from watch"

**Comment by MortenHannemose** [comment]
Just leaving this here in case it helps someone else: The log can be viewed by calling:
 ```adb logcat -e "Unhandled request from watch"```
