### ISSUE TITLE
GadgetBridge not automatically installing app after make

### ISSUE THREAD

**Issue by MortenHannemose** [dakhnod/Fossil-HR-SDK#12]
I have gotten the code to build using `make` and it is succesfully copied to my phone. However, GadgetBridge does not automatically install the app. This is the last part of the output after calling `make`.

```adb push build/snakeApp.wapp /sdcard/snakeApp.wapp
build/snakeApp.wapp: 1 file pushed. 0.1 MB/s (8210 bytes in 0.063s)
adb shell am broadcast \
    -a "nodomain.freeyourgadget.gadgetbridge.Q_UPLOAD_FILE" \
    --es EXTRA_HANDLE APP_CODE \
    --es EXTRA_PATH "/sdcard/snakeApp.wapp" \
--ez EXTRA_GENERATE_FILE_HEADER false
Broadcasting: Intent { act=nodomain.freeyourgadget.gadgetbridge.Q_UPLOAD_FILE flg=0x400000 (has extras) }
Broadcast completed: result=0
```

When I use GadgetBridge to manually install the app it works, it's just the automatic install that I can't figure out. GadgetBridge does have storage permission and is version 0.68.0.
I hope you can help me debug this :)

**Comment by arjan-s** [comment]
No problem, you probably didn't know you need to enable a setting for that. Go into your Gadgetbridge device settings, then Developer settings, then enable "Allow dangerous external intents".

**Comment by MortenHannemose** [comment]
Thanks, now it works perfectly :)
