### ISSUE TITLE
How to launch another app?

### ISSUE THREAD

**Issue by MortenHannemose** [dakhnod/Fossil-HR-SDK#13]
I'm working on creating a more responsive circular menu. But I can't figure out how to actually launch a different app from my app? Any input on how this could be accomplished would be much appreciated.

**Comment by arjan-s** [comment]
Sounds interesting! Our (not circular) watchface menu does that too, take a look here: https://codeberg.org/Freeyourgadget/fossil-hr-watchface/src/commit/6b3754690359b8ae964d73d18e607d4631e1eaf2/open_source_watchface.js#L197

**Comment by MortenHannemose** [comment]
Wow, I am already using your menu and it's absolutely amazing! I didn't know it was also written with the same javascript. 

I'm working off the example in simple-menu. I have added 
```
	response.open_app = function(appName){
            response.action = {
                type: 'open_app',
                node_name: appName,
                class: 'watch_app',
            }
        }
```
to the wrapped responses in the simple-menu example, but when I call
```
response.open_app("timerApp");
```
nothing appears to happen. I have tried following it up with a call to `state_machine.set_current_state('background');` but that doesn't change anything. Any ideas on what I am missing? I can also share my entire `app.js` if you would like.

**Comment by MortenHannemose** [comment]
I have experimented quite a bit and have figured a few things out

- When I compile the opensource watchface, app opening is working
- It must be `class: 'watch_app'` in order for to app opening to work
- When I change the version in `app.json` of the opensource watchface from `1.2.0.0` to `2.2.0.0` it no longer works

I figure that the changing the first digit of the version number to `2` makes it into a regular app, instead of a watchface (as it no longer auto launches or takes over what "home" does). My guess is that it somehow changes the class of the app as well, so `watch_app` is no longer the correct class to specify when trying to open an app. 

I'm kinda stuck on how to proceed from here, but I thought I'd share my findings.

**Comment by MortenHannemose** [comment]
I think I could work this out if I had `launcherApp.wapp` (from the V5 version of the app) to take apart. Could someone that has already downloaded it send it to me? 
Alternatively, I could try intercepting it myself, but I'm not sure how how to go about that, as I haven't found any instructions on how to do it.
Any help will be greatly appreciated :)

**Comment by arjan-s** [comment]
That's definitely possible, although it's very labor intensive. I've decompiled many of those apps from bytecode back to jerryscript. I've also started on the launcherApp, but I've stopped because I didn't want to put so much time in it anymore. Instead, I started working on an automatic decompiler, which is a lot of work but much more fun and rewarding. If you are on the Gadgetbridge Matrix room, we can have a chat if you want and I can provide the launcherApp or some examples.

**Comment by MortenHannemose** [comment]
Here's what I found out: 
If the app is named `launcherApp` it is able to open other apps on firmware 3.0 (app V5) and newer. 
For older firmwares, I have only managed to make the watchface itself open apps, which makes sense as the launcher is part of the watchface on those firmwares.
