### ISSUE TITLE
Centering text?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#14]
Is there a way to center text with the JSON layout engine?  The `container` type has some alignment parameters documented, although they didn't seem to work with the `text` type.

**Comment by MortenHannemose** [comment]
Take a look at the title (10th id) of the custom menu. https://codeberg.org/Freeyourgadget/fossil-hr-watchface/src/branch/main/build/files/layout/menu_layout

It uses relative placement with the correct alignment options set in the parent container to obtain a centered text.
