### ISSUE TITLE
Current second?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#15]
Is there a way to find the current second of the time?  `current` only has `hour` and `minutes` documented and `now()` seems to return milliseconds since boot, not since epoch or other synchronized source.

**Comment by dakhnod** [comment]
I am somehow getting the epoch timestamp for the alarm function in my stopwatch...

**Comment by osresearch** [comment]
With `now()`? Maybe I misinterpreted the result.  I'll give it another try.

**Comment by osresearch** [comment]
I just rebooted the watch and `now() / 1000` is returning 24, rather than the expected 1661597307.

**Comment by osresearch** [comment]
Where does the alarm function use seconds since epoch? It appears to wrap the `common.hour` and `common.minute` in `get_current_time()` without using seconds anywhere. https://github.com/dakhnod/Fossil-HR-SDK/blob/41833b8146ac9e9b5fd8ee071575a7e4ab4a68c8/examples/timer/app.js#L107

**Comment by osresearch** [comment]
Ah, it calls `get_unix_time()`, which isn't documented in the readme.  That does appear to return a result that is close enough (but not exactly) the same as the output of `date '+%s'`.
