### ISSUE TITLE
Lat/Lon position from gadgetbridge?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#17]
The gadgetbridge app on the phone knows the lat/lon of the device; is this exported to the SDK in the `common` structure or through some other mechanism?

**Comment by osresearch** [comment]
Of the ones that looked promising, `common.settings` is undefined and `common.weatherInfo` is empty.

**Comment by arjan-s** [comment]
Nope, the coordinates are not sent to the watch because it doesn't do anything with them. You can, however, send custom data to any app. So you could use for instance Tasker or Easer to send an Intent with the data you want to your watchface code [like this](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Fossil-Hybrid-HR#custom-menu).

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/187901711-1ff2a9a6-4906-4c12-b1fe-2f9083aa8b97.png)

Computing things like sunrise / sunset need the lat/lon, and since gadgetbridge is already tracking the location it seems like using a separate application is unnecessarily compilcated. What would it take to expose the information, similar to the way the timezone, units or other configuration is sent to the watch?

**Comment by dakhnod** [comment]
GB is not tracking the location.

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/187909024-fd240288-0230-4c3f-893c-88898222b517.png)

Under `Settings` - `Acquire Location` it seems to have the current lat/lon.

**Comment by dakhnod** [comment]
Yes, it reads the location once when you click it. Not continuously.

**Comment by osresearch** [comment]
That's fine; how can I expose that information to the watch face since GB knows it?

(Although the option `Keep Location Updated` seems like it is doing more often)

**Comment by dakhnod** [comment]
Not sure if it makes sense to send the location to the watch from GB.
Do you want to calculate the position of the planets on the watch?

**Comment by osresearch** [comment]
Yes, the goal is to do all of the math on the watch.

What would be the reason to not expose the location data? It seems like it is in the same category as time zone and other settings that can be configured via the app.

**Comment by dakhnod** [comment]
Timezone and all the other settings are sent to the watch via fossil's protocol.
That protocol doesn't support gps date...

**Comment by osresearch** [comment]
> [...] You can, however, send custom data to any app. So you could use for instance Tasker or Easer to send an Intent with the data you want to your watchface code [like this](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Fossil-Hybrid-HR#custom-menu).

Since the default protocol doesn't send the location data, I'm trying to set the value based on this example with `adb am broadcast` and can see in the logs that the message is being forwarded, but the `this.config` structure isn't being updated.

In the `app.js` I have:
```
        "config": {
                "lat": 52.3676,
                "lon": 4.9041
        },
```

Then I run the command to update the latitude (For the time being I'm replacing the `stopwatchApp` with my own, so that it show sup in the circle menu):

```
am broadcast \
  -a "nodomain.freeyourgadget.gadgetbridge.Q_PUSH_CONFIG" \
  --es EXTRA_CONFIG_JSON \
  '{"push":{"set":{"stopwatchApp._config.lat":0}}}'
```

In the logs I see a hex dump that corresponds to that string:
```
09-01 15:59:37.300 12661 13385 D nodomain.freeyourgadget.gadgetbridge.service.btle.actions.WriteAction: writing to characteristic: 3dda0004-957f-7d4a-34a6-74696673696d: 0x00 0x7b 0x22 0x70 0x75 0x73 0x68 0x22 0x3a 0x7b 0x22 0x73 0x65 0x74 0x22 0x3a 0x7b 0x22 0x73 0x74 0x6f 0x70 0x77 0x61 0x74 0x63 0x68 0x41 0x70 0x70 0x2e 0x5f 0x63 0x6f 0x6e 0x66 0x69 0x67 0x2e 0x6c 0x61 0x74 0x22 0x3a 0x30 0x7d 0x7d 0x7d
09-01 15:59:37.305 12661 18237 D nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic write: 3dda0004-957f-7d4a-34a6-74696673696d (success)
```

On the watch face I can see that the `this.config.lat` value is not updated and still has the original value.

**Comment by arjan-s** [comment]
Looks like it's caused by a typo, you used `stopwatchApp._config` instead of `stopwatchApp._.config`.

**Comment by osresearch** [comment]
Ah, that fixed it.  Thanks!  For future searchers, the command requires both `._.config` and extra literal quotes due to `adb shell` also expanding some quotes when it forwarded the command to the phone:
```
adb shell am broadcast \
-a "nodomain.freeyourgadget.gadgetbridge.Q_PUSH_CONFIG" \
--es EXTRA_CONFIG_JSON \
\''{"push":{"set":{"stopwatchApp._.config.position":{"lat":77.8750,"lon":20.9752,"alt":0.0000}}}}'\'
```

(although also for future hackers, it seems that the `config` is overwritten when the app is exited and restarted?)
