### ISSUE TITLE
Images stop being drawn sometimes

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#19]
![image](https://user-images.githubusercontent.com/3068843/187885047-074066cf-59c7-4f2f-8ccc-b92cda802b2c.png)

Occasionally (once per week?) my application will stop drawing images and when I exit it back to the main watchface or app menu, there are no images there either.  Rebooting the watch fixes it for a while.

**Comment by arjan-s** [comment]
Sounds like some kind of memory issue. I don't see this happening with the Gadgetbridge watchface code.
