### ISSUE TITLE
Lost the circle menu?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#20]
![image](https://user-images.githubusercontent.com/3068843/187941886-7905d3c0-df16-4d09-a2c8-9f9cfb304aa5.png)

Somehow I seem to have lost the circle menu? Pressing the middle button does nothing. Holding it in a for a short period brings up the `Disconnect & reset` / `Home` / `Regulatory` menu.  Holding it for a long while reboots the watch, but it comes back up in what looks like a default watch face (no circles, just steps, heart and a date).

Is there a way to ask GB to reinstall the default firmware?

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/187964697-910d01b5-453b-446a-ab42-684588d4871d.png)

I built and installed the [fossil-hr-watchface](https://codeberg.org/Freeyourgadget/fossil-hr-watchface), although this did not restore the circle menu, either.  The middle button does not trigger any functions and if I hold in the bottom button it displays the "`Can't launch app`" error message.

**Comment by arjan-s** [comment]
Looks like you're missing the launcherApp somehow. You can check in the Gadgetbridge app manager whether it is still installed on your watch. If not the easiest way to restore it is to connect the official app again and sync it.

**Comment by osresearch** [comment]
I had to do a full reset and reconnect it to the official app to get them back.  It worked for a while, but something in my app is occasionally causing problems and it has failed in a similar way again.  This time there is *zero* text or images displayed in the main app and no menu, so I to avoid re-pairing it, I've assigned a physical button to launch my app instead.
