### ISSUE TITLE
Maximum app size?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#21]
I seem to be unable to upload apps larger than around 160 KB.  I've added a few new images to my watch and when the total size goes past about that amount the upload eventually times out and now the watch is back in the weird state I described n #20 . If I down-scale the images slightly to stay under some magic size, it seems to upload and run fine.

**Comment by osresearch** [comment]
165212 bytes fails to upload, 163668 bytes works. Sometimes the upload corrupts the app in place and I have to do a long-middle button reset to get the watch back into a good state.

**Comment by dakhnod** [comment]
Maybe that has to do with the upload request, since the MTU is only 200 bytes or something...
