### ISSUE TITLE
Support for V3.0 firmware?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#24]
![IMG_7308](https://github.com/dakhnod/Fossil-HR-SDK/assets/3068843/b7fc47fb-801d-489d-a5c2-9cb5b3b391ed)

I upgraded to a new phone and re-paired my Skagen Hybrid Gen 6 watch with it using the official app, which also upgraded to the VA0.0.3.0r.v18 firmware.  My old watches like https://github.com/osresearch/moon-watch can be installed, but they no longer run. They just draw a black screen with the hands at 9 o'clock.

Is it possible to downgrade the firmware or is there a way to rebuild the watch application to support v3.0?

**Comment by gjkrediet** [comment]
You can downgrade to earlier version of the firmware bij using an older version of the official fossil app. You can obtain these for example from: https://www.apkmirror.com/apk/fossil-group/fossil-smartwatches/

**Comment by arjan-s** [comment]
Actually, I'm pretty certain that the gen 6 watches never had a 2.x firmware. You're free to try of course, and please let us know the results. :)
