### ISSUE TITLE
Possible to send image to fossil watch without Gadgetbridge

### ISSUE THREAD

**Issue by caichunjian520** [dakhnod/Fossil-HR-SDK#25]
I didn't see any bluetooth protocol to send image to watch, so is it possible?

**Comment by dakhnod** [comment]
what are you trying to achieve?

**Comment by caichunjian520** [comment]
I just want to know the protocol to send full image to fossil watch as watch face.

**Comment by dakhnod** [comment]
Do you want to send a whole watchface, or only update the background for a running watchface? Do you have the custom watchface installed, yet?

**Comment by caichunjian520** [comment]
I want to send whole watchface. 
I would like to write a mobile app to send full 240 x 240 dithering image to the watch. I have worked on some bluetooth printer and other e-ink display screen. So it is easy for me to get get byte array from the binary image. I am concerned about the protocol to send image bytes to watch and if it needs auth key from fossil web server to make it work?

**Comment by dakhnod** [comment]
You should be able to find everything you need in the Gadgetbridge code, or, if you're willing to use Gadgetbridge as a proxy, you can just direct it to send the watchface app.
