### ISSUE TITLE
Store global variables

### ISSUE THREAD

**Issue by gjkrediet** [dakhnod/Fossil-HR-SDK#26]
Global variables like 'total_sleep' and 'weatherinfo' which are accessible by any program can be retreived and set by get_common(). But did you know that you can also store your own variables in this global space? For example you can do a store with  get_common().V('myVariable', value) and retreive it in the same app or watchface or even another one with  value = get_common().U('myVariable'). Variables can also be JSON strings for example and I have done so in a few apps of my own, without running into limitations. I don't know however how much space is available for global variables. The global variables survive a reboot of the watch. Using globals across apps has its own risks but who doesn't want to live dangerously?

**Comment by dakhnod** [comment]
Thanks for the headsup
