### ISSUE TITLE
Microphone access

### ISSUE THREAD

**Issue by Plasny** [dakhnod/Fossil-HR-SDK#27]
How can I get audio from watch's built-in microphone and send it to my phone? Do you know how AlexaApp achives it?

**Comment by dakhnod** [comment]
Yep, there's an Extension system in GB. You have to write your own App that receives the OPUS Data and decodes it.

**Comment by Plasny** [comment]
Can I start the listening process from my own app or does it listen all the time?

**Comment by dakhnod** [comment]
Actually, you use the AlexaApp. When you open AlexaApp on the watch, the microphone gets activated and streamed to the phone. There, GB attempts to find a handler application and forwards the OPUS stream there.

**Comment by Plasny** [comment]
Alright, is there a way to open an app from another app then?

**Comment by dakhnod** [comment]
On the watch? Yep. My watchface menu does it.

**Comment by gjkrediet** [comment]
I think you can start an app from a watchface but not from another app.

**Comment by dakhnod** [comment]
https://codeberg.org/Freeyourgadget/fossil-hr-watchface/src/branch/main/open_source_watchface.js#L194-L200

**Comment by dakhnod** [comment]
> I think you can start an app from a watchface but not from another app.

possibly. Did you try it?

**Comment by gjkrediet** [comment]
Yes. Discussed it with @Arjen-s but neither of found a solution.

**Comment by gjkrediet** [comment]
The Fossil launcherApp can - by the way - start other apps but self-written apps cannot, not even if one names it launcherApp

**Comment by Plasny** [comment]
Ok, so I cannot open app from another app. I will need to use the watchface for it. Can I access the microphone then? Or is it also only available for Fossil's AlexaApp?

**Comment by arjan-s** [comment]
> The Fossil launcherApp can - by the way - start other apps but self-written apps cannot, not even if one names it launcherApp

Actually, a custom launcherApp exists and can launch other apps. Sadly I don't have the code though. And ideed apps with other names than that can't launch apps.

**Comment by dakhnod** [comment]
@Plasny mind sharing what you're trying to achieve?

**Comment by Plasny** [comment]
I wanted to record short messages with my watch and add some tags to these recordings also using watch and save them on my phone with another app i would write

**Comment by arjan-s** [comment]
> Ok, so I cannot open app from another app. I will need to use the watchface for it. Can I access the microphone then? Or is it also only available for Fossil's AlexaApp?

If you're going to be coding anyway, it's probably best to build your own app that can be triggered by a signal from GB to start recording and streaming. How to do the recording and streaming can be copied from how AlexaApp does it.

**Comment by dakhnod** [comment]
If you want to trigger the recordings from the watch, you can just use the custom menu to start the AlexaApp, no?

**Comment by dakhnod** [comment]
If you want to trigger the recording from the phone, you can also use the custom watchface and menu.

**Comment by Plasny** [comment]
yeah you are right, I can add tags later. It doesn't need to be all in one. Thanks a lot for help

**Comment by dakhnod** [comment]
You could generate tags from the spoken text, somehow...

**Comment by dakhnod** [comment]
also, please close the issue if this is solved.

**Comment by Plasny** [comment]
Thanks for your amazing work and help.
