### ISSUE TITLE
Cannot install / launch installed examples

### ISSUE THREAD

**Issue by JetErorr** [dakhnod/Fossil-HR-SDK#28]
I am very new to the SDK and Gadgetbridge. For now I'm just looking to run the sample apps and understand the capabilities and limitations of the SDK and the watch, which I will use to formulate apps some months down the line. I have not been able to install / launch the example apps. 

I tried: 
1. Running `make` in the snake and simpleMenu example dirs: It runs without issues (see log below), but I do not see the app on the launcher, or GB. 

2. Copying the .wapp over to my phone and installing it via GB: No app in launcher, but now appears in GB. 
2.1 Tapped 'Launch' from GB, no change. 

So far I have: 
Installed the prerequisites on a Ubuntu WSL2 instance, 
Connected my Android 14 phone via wired ADB, 
Connected my *test watch via GB on the ADB'd phone, 
Updated the Makefile to use 'adb.exe' instead of just 'adb' (this was a solution to find devices direct from WSL2, without a :5555 "bridge" from Windows 10), 
Checked and corrected the IP address in the Makefile. 

I could be very clueless about things as this is literally my first hour working with the SDK, GB, the watch's code, etc. Feel free to point out noob stuff. 

Make Log: 
```
mkdir -p build/files/code build/files/config
jerry-snapshot generate -f '' app.js -o build/files/code/snakeApp
Input file 'app.js' (7961 bytes) loaded.
Created snapshot file: 'build/files/code/snakeApp' (3406 bytes)
python3 ../../tools/pack.py -i build/ -o build/snakeApp.wapp
packing snakeApp
packing !icon_lg
packing !icon_sm
packing icHome
packing snake_layout
packing display_name
build/snakeApp.wapp: 1 file pushed, ...ed. 22.0 MB/s (8394 bytes in 0.000s)
adb.exe shell am broadcast \
-a "nodomain.freeyourgadget.gadgetbridge.Q_UPLOAD_FILE" \
--es EXTRA_HANDLE APP_CODE \
--es EXTRA_PATH "/sdcard/Android/data/nodomain.freeyourgadget.gadgetbridge/files/make/snakeApp.wapp" \
--ez EXTRA_GENERATE_FILE_HEADER false
Broadcasting: Intent { act=nodomain.freeyourgadget.gadgetbridge.Q_UPLOAD_FI
LE flg=0x400000 (has extras) }
Broadcast completed: result=0
```

*I have 2 Colliders, 1 connected via GB, 1 connected via the official app (will switch once I can replicate the sleep tracking algo. of the official app). I have them connected simultaneously, which could be a problem, but I am not sure if it is. 

Thank you for your time.

**Comment by dakhnod** [comment]
You should be able to take the snakeApp.wapp file, transfer it to your phone somehow, and then install it from GB. Just click on the apps icon on the device card, press the upload button and select the .wapp file.

An issue might be that the FW on the watch will not display apps with a non-standard name...

Also, the sleep tracking algo is found in a .so file within the official app. Probably an AI model or something. Good luck in any case...
