### ISSUE TITLE
Some info about building the deps

### ISSUE THREAD

**Issue by Taiiwo** [dakhnod/Fossil-HR-SDK#5]
I just thought I'd leave some information about what I had to do to get jerryscript to build for this project.

Get jerryscript from https://github.com/jerryscript-project/jerryscript
run `git checkout 343e800` to get version 2.1.0
Install with `sudo python tools/build.py --snapshot-exec=on --jerry-cmdline-snapshot=on --profile=es5.1` to compile the snapshot binary
Then you need to go into the build folder and run `sudo make` and `sudo make install` to add the items to the path

You'll also need to install jq from your package manager and crc32c from pip, and working adb, for which I recommend using linux and not bothering with WSL networking to a windows adbd.

After that make sure you get your auth keys from the modded version of the fossil APK (You can find this on the reddit), and fully uninstall the fossil app (otherwise your custom apps will get wiped every time you unlock your phone)

**Comment by dakhnod** [comment]
Actually, you don't need any Fossil app to get the Key.
You can also use my [Authenticator app](https://github.com/dakhnod/FossilHRAuthenticator) to get the key.

Anyway, thanks for the heads up

**Comment by osresearch** [comment]
I've created #7 for the `jerry-snapshot` instructions and #8 is a very simple tool to fetch the auth keys, rather than having to build another Android app (or deal with MITM, etc).
