### ISSUE TITLE
snake doesn't work on gen6 hybrid?

### ISSUE THREAD

**Issue by osresearch** [dakhnod/Fossil-HR-SDK#9]
My build of the `timer` demo works on my Skagen gen6 hybrid, but the `snake` application doesn't show up in on-watch menu.  The gadgetbridge app shows it as being installed although there is no icon to select to run it.

**Comment by arjan-s** [comment]
The app will work just fine, it's the menu that's the problem. The new circular menu has a list of apps it can show, and unknown apps will not show up.
Currently the only alternative for running custom apps is the custom menu (see the Fossil wiki page on the Gadgetbridge repo).

**Comment by dakhnod** [comment]
@osresearch you could rename the snake app to stopwatchApp or something, so the watch recognizes the name.

I didn't know about the menu limitations, though...

**Comment by osresearch** [comment]
Yeah, I've been naming my watch face `stopwatchApp` so that I can select it directly.

**Comment by arjan-s** [comment]
@osresearch Cool, you're working on a watchface? Do you know that they're a special kind of watch app? They can have any name too, and don't have to replace other apps. If you have multiple installed, you can switch between them using the installed watchfaces screen in Gadgetbridge. For the code and structure, you can take a look at [the Gadgetbridge watchface code](https://codeberg.org/Freeyourgadget/fossil-hr-watchface) for inspiration!
